// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: internal/transport/grpc/proto/email.proto

package emailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Html          string                 `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	Cc            []string               `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,6,rep,name=bcc,proto3" json:"bcc,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_internal_transport_grpc_proto_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *SendEmailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_internal_transport_grpc_proto_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_transport_grpc_proto_email_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_proto_email_proto_rawDesc = "" +
	"\n" +
	")internal/transport/grpc/proto/email.proto\x12\x05email\"\xa1\x01\n" +
	"\x10SendEmailRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04html\x18\x04 \x01(\tR\x04html\x12\x0e\n" +
	"\x02cc\x18\x05 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x06 \x03(\tR\x03bcc\x12\x19\n" +
	"\breply_to\x18\a \x01(\tR\areplyTo\"#\n" +
	"\x11SendEmailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2I\n" +
	"\fEmailService\x129\n" +
	"\x04Send\x12\x17.email.SendEmailRequest\x1a\x18.email.SendEmailResponseB'Z%internal/transport/grpc/proto/emailpbb\x06proto3"

var (
	file_internal_transport_grpc_proto_email_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_email_proto_rawDescData []byte
)

func file_internal_transport_grpc_proto_email_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_email_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_email_proto_rawDesc), len(file_internal_transport_grpc_proto_email_proto_rawDesc)))
	})
	return file_internal_transport_grpc_proto_email_proto_rawDescData
}

var file_internal_transport_grpc_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_grpc_proto_email_proto_goTypes = []any{
	(*SendEmailRequest)(nil),  // 0: email.SendEmailRequest
	(*SendEmailResponse)(nil), // 1: email.SendEmailResponse
}
var file_internal_transport_grpc_proto_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.Send:input_type -> email.SendEmailRequest
	1, // 1: email.EmailService.Send:output_type -> email.SendEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_email_proto_init() }
func file_internal_transport_grpc_proto_email_proto_init() {
	if File_internal_transport_grpc_proto_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_email_proto_rawDesc), len(file_internal_transport_grpc_proto_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_email_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_email_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_email_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_email_proto = out.File
	file_internal_transport_grpc_proto_email_proto_goTypes = nil
	file_internal_transport_grpc_proto_email_proto_depIdxs = nil
}
